---
aws:
  region: overwrite-me
  library:
    s3_bucket: overwrite-me
    s3_path: library

aem_opencloud:
  version: 4.1.0-pre.1
  config:
    artifact_url: https://overwrite-me/overwrite-me.tar.gz
  custom_manager_steps:
    artifact_url:
  custom_image_provisioner:
    artifact_url:
  custom_stack_provisioner:
    artifact_url:
  descriptors:
    consolidated:
      deployment_descriptor_url:
      export_descriptor_url:
      content_healthcheck_descriptor_url:
    full-set:
      deployment_descriptor_url:
      export_descriptor_url:
      content_healthcheck_descriptor_url:
  jenkins_sharedlibs:
    repo_url: https://github.com/shinesolutions/aem-opencloud-manager
    repo_branch: master

jenkins:
  protocol: http
  host: overwrite-me
  port: 8080
  username: overwrite-me
  password: overwrite-me
  agent:
    docker_image: 'shinesolutions/aem-platform-buildenv:0.11.0'
    docker_args: ''
  os:
    jenkins_home:
    user:
    group:

user_resources:
  aws:
    resource_prefix: overwrite-me
    vpc_id: overwrite-me
