---
- name: AEM OpenCloud Manager Jenkins installer
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: "Create Jenkins Jobs"
      jenkins_job:
        config: "{{ lookup('file', '../../../stage/jenkins/jobs/{{ item.path }}') }}"
        name: "{{ item.path| replace('/config.xml', '') }}"
        password: "{{ jenkins.password }}"
        url: "{{ jenkins.url }}:{{ jenkins.port }}"
        user: "{{ jenkins.username }}"
      with_filetree: ../../../stage/jenkins/jobs
      when: item.state == 'file'
