# aws:
#   library:
#     s3_bucket: aem-opencloud
#
# aem_opencloud:
#   version: 3.x
#   config:
#     artifact_url: https://github.com/shinesolutions/aem-helloworld-config/archive/master.tar.gz
#   manager:
#     repo_url: https://github.com/shinesolutions/aem-opencloud-manager
#     repo_branch: master
#
# jenkins:
#   username: overwrite-me
#   password: overwrite-me

aws:
  library:
    s3_bucket: overwrite-me
    s3_path: library

aem_opencloud:
  version: 3.x
  config:
    artifact_url: https://github.com/shinesolutions/aem-helloworld-config/archive/master.tar.gz
  manager:
    repo_url: overwrite-me
    repo_branch: master

jenkins:
  protocol: http
  host: localhost
  port: 8080
  username: overwrite-me
  password: overwrite-me
